# Generated by Django 3.2 on 2023-05-30 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('house_number', models.CharField(blank=True, max_length=100, verbose_name='Номер дома')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Улица')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Адрес пользователя',
                'verbose_name_plural': 'Адреса пользователей',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='ID телеграм')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('driver', 'Водитель'), ('admin', 'Администратор'), ('UK', 'УК')], default='user', max_length=10, verbose_name='Роль')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('phone_number', models.CharField(blank=True, max_length=100, verbose_name='Номер телефона')),
                ('ban', models.BooleanField(default=False, verbose_name='Бан пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата входа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
            },
        ),
        migrations.CreateModel(
            name='TemplateUk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='краткое наименование шаблона')),
                ('template', models.TextField(verbose_name='Текст для рассылки')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time_start', models.TimeField(verbose_name='Время начала')),
                ('time_end', models.TimeField(verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'Шаблон УК',
                'verbose_name_plural': 'Шаблоны УК',
            },
        ),
        migrations.CreateModel(
            name='AddressUK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(blank=True, max_length=20, null=True, verbose_name='Псевдоним')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('address', models.ManyToManyField(related_name='address_uk', to='main.Address', verbose_name='Адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'УК',
                'verbose_name_plural': 'УК',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.telegramuser', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='NumberCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер авто')),
                ('default_num', models.BooleanField(default=False, verbose_name='Номер по умолчанию')),
                ('vin', models.CharField(blank=True, max_length=200, null=True, verbose_name='VIN')),
                ('car_brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Марка авто')),
                ('car_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель авто')),
                ('car_year', models.BigIntegerField(blank=True, null=True, verbose_name='Год авто')),
                ('power', models.CharField(blank=True, max_length=100, null=True, verbose_name='Мощность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Авто пользователя',
                'verbose_name_plural': 'Авто пользователей',
                'unique_together': {('user', 'car_num')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('user', 'address')},
        ),
    ]
